import { getCurrentYearAndMonth, prettyMonthYear } from "@/functions/helper";

export const personalInfoInputs = [
  {
    label: "Full Name",
    name: "fullName",
    type: "text",
    value: "",
    pattern: "^[A-Za-z]{2,}[ '-][A-Za-z.]+$",
    placeholder: "John Doe",
    required: true,
    hasValidValue: false,
    warningMessage:
      "Please Enter first and last name separated by space, hyphen, or apostrophe.",

    id: 1,
  },
  {
    label: "Profession",
    name: "profession",
    type: "text",
    value: "",
    pattern: "^[A-Za-z][A-Za-z /&.-]{1,49}$",
    placeholder: "Software Engineer",
    required: true,
    hasValidValue: false,
    warningMessage:
      "Please enter a valid profession (letters and / & . - allowed).",
    id: 2,
  },
  {
    label: "Email Address",
    name: "email",
    type: "email",
    value: "",
    pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}$",
    placeholder: "john.doe@example.com",
    required: true,
    hasValidValue: false,
    warningMessage: "Please enter a valid email, (e.g. name@example.com.)",
    id: 3,
  },
  {
    label: "Address",
    name: "address",
    type: "text",
    value: "",
    pattern: "^[A-Za-z0-9s,.'-/ ]{2,100}$",
    placeholder: "City, Country (e.g. Baghdad, Iraq)",
    required: false,
    hasValidValue: true,
    warningMessage: "Please enter a valid address (e.g., City, Country).",
    id: 4,
  },
];

export const experienceInputs = [
  {
    label: "Job Title / Role",
    name: "role",
    type: "text",
    value: "",
    pattern: "^[A-Za-z][A-Za-z /&.-]{1,49}$",
    placeholder: "Front-End Developer",
    required: true,
    hasValidValue: false,
    warningMessage:
      "Please enter a valid job title (letters and / & . - allowed).",
    id: 1,
  },
  {
    label: "Company Name",
    name: "company",
    type: "text",
    value: "",
    pattern: "^[a-zA-Z0-9&.\\-,' ]{2,50}$",
    placeholder: "Google",
    required: true,
    hasValidValue: false,
    warningMessage:
      "Please enter a valid company name (letters, numbers, & . - , ' allowed).",
    id: 2,
  },
  {
    label: "Start Date",
    name: "startDate",
    type: "month",
    value: "",
    min: "1990-01",
    max: getCurrentYearAndMonth(),
    placeholder: "January 1990",
    required: true,
    hasValidValue: false,
    warningMessage:
      "Please select a valid start date (from Jan 1990 to today).",
    id: 3,
  },
  {
    label: "End Date",
    name: "endDate",
    type: "month",
    max: getCurrentYearAndMonth(),
    placeholder: prettyMonthYear(getCurrentYearAndMonth()),
    value: "",
    required: true,
    hasValidValue: false,
    disabled: false,
    warningMessage: "Please select a valid end date (from Jan 1990 to today).",
    id: 4,
  },
  {
    label: "Job Description",
    name: "description",
    type: "textarea",
    value: "",
    pattern: "^.{30,800}$",
    placeholder: "Describe your responsibilities, achievements, and skills...",
    required: true,
    hasValidValue: false,
    warningMessage: "Please enter 30 to 800 characters describing your job.",
    id: 5,
  },
  {
    label: "Currently work here",
    name: "currentlyWorking",
    type: "checkbox",
    value: false,
    required: false,
    hasValidValue: true,
    id: 6,
  },
];

export const techSkillsInputs = [
  {
    label: "Skill 1",
    name: "skill1",
    type: "text",
    value: "",
    pattern: "^[a-zA-Z0-9.+\\-]{2,30}$",
    placeholder: "JavaScript",
    required: true,
    hasValidValue: false,
    warningMessage:
      "Please enter a valid skill (2-30 chars, letters, numbers, . + -).",
    id: 1,
  },
  {
    label: "Skill 2",
    name: "skill2",
    type: "text",
    value: "",
    pattern: "^[a-zA-Z0-9.+\\-]{2,30}$",
    placeholder: "React",
    required: true,
    hasValidValue: false,
    warningMessage:
      "Please enter a valid skill (2-30 chars, letters, numbers, . + -).",
    id: 2,
  },
  {
    label: "Skill 3",
    name: "skill3",
    type: "text",
    value: "",
    pattern: "^[a-zA-Z0-9.+\\-]{2,30}$",
    placeholder: "Node.js",
    required: true,
    hasValidValue: false,
    warningMessage:
      "Please enter a valid skill (2-30 chars, letters, numbers, . + -).",
    id: 3,
  },
  {
    label: "Skill 4",
    name: "skill4",
    type: "text",
    value: "",
    pattern: "^[a-zA-Z0-9.+\\-]{2,30}$",
    placeholder: "MongoDB",
    required: true,
    hasValidValue: false,
    warningMessage:
      "Please enter a valid skill (2-30 chars, letters, numbers, . + -).",
    id: 4,
  },
];

export const educationInputs = [
  {
    label: "University Name",
    name: "universityName",
    type: "text",
    value: "",
    pattern: "^[a-zA-Z0-9&.\\- ']{3,100}$",
    placeholder: "University of Lagos",
    required: false,
    hasValidValue: true,
    warningMessage:
      "Please enter a valid university name (3-100 chars, letters, numbers, & . - allowed).",
    id: 1,
  },
  {
    label: "University Location",
    name: "universityLocation",
    type: "text",
    value: "",
    pattern: "^[a-zA-Z0-9,.\\-\\/ ]{2,50}$",
    placeholder: "Lagos",
    required: false,
    hasValidValue: true,
    warningMessage:
      "Please enter a valid university location (2-50 chars, letters, numbers, , . - / allowed).",
    id: 2,
  },
  {
    label: "Degree / Program",
    name: "degree",
    type: "text",
    pattern: "^[a-zA-Z0-9\\/&.\\-' ]{2,100}$",
    value: "",
    placeholder: "Bachelor of Science",
    required: false,
    hasValidValue: true,
    warningMessage:
      "Please enter a valid degree or program (2-100 chars, letters, numbers, / & . - allowed).",
    id: 3,
  },
  {
    label: "Field of Study",
    name: "fieldOfStudy",
    type: "text",
    pattern: "^[a-zA-Z0-9\\/&.\\-' ]{2,70}$",
    value: "",
    placeholder: "Computer Science",
    required: false,
    hasValidValue: true,
    warningMessage:
      "Please enter a valid field of study (2-70 chars, letters, numbers, / & . - allowed).",
    id: 4,
  },
  {
    label: "Graduation Date",
    name: "graduationDate",
    type: "month",
    value: "",
    min: "1990-01",
    max: getCurrentYearAndMonth(),
    placeholder: prettyMonthYear(getCurrentYearAndMonth()),
    required: false,
    hasValidValue: true,
    warningMessage:
      "Please select a valid graduation date (from Jan 1990 to today).",
    id: 5,
  },
];

export const contactInfoInputs = [
  {
    label: "Phone Number",
    name: "phoneNumber",
    type: "tel",
    pattern: "^\\+?[\\d\\-(). ]{7,20}$",
    value: "",
    placeholder: "+1 (123) 456-7890",
    required: true,
    hasValidValue: false,
    warningMessage: "Please enter a valid phone number (7-20 digits).",
    id: 5,
  },
  {
    label: "Linkedin Profile Link",
    name: "linkedin",
    type: "text",
    pattern: "^(https?:\\/\\/(www\\.)?)?linkedin\\.com\\/.*$",
    value: "",
    placeholder: "www.linkedin.com/in/moamal-alaa",
    required: true,
    hasValidValue: false,
    warningMessage: "Please copy/paste your full LinkedIn profile URL",
    id: 6,
  },
  {
    label: "GitHub Profile Link",
    name: "github",
    type: "text",
    pattern: "^(https?:\\/\\/(www\\.)?)?github\\.com\\/[A-Za-z0-9_-]+\\/?$",
    value: "",
    placeholder: "github.com/Moamal-2000",
    required: true,
    hasValidValue: false,
    warningMessage: "Please copy/paste your full GitHub profile URL",
    id: 7,
  },
  {
    label: "Portfolio Link",
    name: "portfolio",
    type: "text",
    pattern: "^https?:\\/\\/.+$",
    value: "",
    placeholder: "moamalalaa.netlify.app",
    required: false,
    hasValidValue: false,
    warningMessage: "Please enter a valid URL.",
    id: 8,
  },
];

export const certificationInputs = [
  {
    label: "Certification Name",
    name: "certification1",
    type: "text",
    value: "",
    pattern: "^[a-zA-Z0-9\\/&.\\-#' ]{2,100}$",
    placeholder: "Certificate of Engineering",
    required: false,
    hasValidValue: true,
    warningMessage:
      "Please enter a valid certification name (2-100 chars, letters, numbers, & . - # allowed).",
    id: 1,
  },
  {
    label: "Certificate URL",
    name: "certificationUrl1",
    type: "url",
    value: "",
    placeholder: "https://example.com/certificate",
    required: false,
    hasValidValue: true,
    warningMessage: "Please enter a valid certificate URL.",
    id: 2,
  },
];
