export const personalInfoInputs = [
  {
    label: "Full Name",
    name: "fullName",
    type: "text",
    value: "",
    pattern: "^[A-Za-z]{2,}([ '-][A-Za-z.]+)*$",
    placeholder: "John Doe",
    required: true,
    hasValidValue: false,
    id: 1,
  },
  {
    label: "Profession",
    name: "profession",
    type: "text",
    value: "",
    pattern: "^[A-Za-z][A-Za-z /&.-]{1,49}$",
    placeholder: "Software Engineer",
    required: true,
    hasValidValue: false,
    id: 2,
  },
  {
    label: "Email Address",
    name: "email",
    type: "email",
    value: "",
    pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}$",
    placeholder: "john.doe@example.com",
    required: true,
    hasValidValue: false,
    id: 3,
  },
  {
    label: "Address",
    name: "address",
    type: "text",
    value: "",
    pattern: "^[A-Za-z0-9s,.'-/]{2,100}$",
    placeholder: "City, Country (e.g. Baghdad, Iraq)",
    required: false,
    hasValidValue: true,
    id: 4,
  },
];

export const experienceInputs = [
  {
    label: "Job Title / Role",
    name: "role",
    type: "text",
    value: "",
    pattern: "^[A-Za-z][A-Za-z /&.-]{1,49}$",
    placeholder: "Front-End Developer",
    required: true,
    hasValidValue: false,
    id: 1,
  },
  {
    label: "Company Name",
    name: "company",
    type: "text",
    value: "",
    pattern: "^[a-zA-Z0-9&.\\-,' ]{2,50}$",
    placeholder: "Google",
    required: true,
    hasValidValue: false,
    id: 2,
  },
  [
    {
      label: "Start Date",
      name: "startDate",
      type: "month",
      value: "",
      min: "1990-01",
      required: true,
      hasValidValue: false,
      id: 3,
    },
    {
      label: "End Date",
      name: "endDate",
      type: "month",
      value: "",
      required: true,
      hasValidValue: true,
      id: 4,
    },
  ],
  {
    label: "Job Description",
    name: "description",
    type: "textarea",
    value: "",
    pattern: "^.{30,800}$",
    placeholder: "Describe your responsibilities, achievements, and skills...",
    required: true,
    hasValidValue: false,
    id: 5,
  },
  {
    label: "Currently work here",
    name: "currentlyWorking",
    type: "checkbox",
    value: false,
    required: false,
    hasValidValue: true,
    id: 6,
  },
];

export const techSkillsInputs = [
  {
    label: "Skill 1",
    name: "skill1",
    type: "text",
    value: "",
    pattern: "^[a-zA-Z0-9.+\\-]{2,30}$",
    placeholder: "JavaScript",
    required: true,
    hasValidValue: false,
    id: 1,
  },
  {
    label: "Skill 2",
    name: "skill2",
    type: "text",
    value: "",
    pattern: "^[a-zA-Z0-9.+\\-]{2,30}$",
    placeholder: "React",
    required: true,
    hasValidValue: false,
    id: 2,
  },
  {
    label: "Skill 3",
    name: "skill3",
    type: "text",
    value: "",
    pattern: "^[a-zA-Z0-9.+\\-]{2,30}$",
    placeholder: "Node.js",
    required: true,
    hasValidValue: false,
    id: 3,
  },
];

export const educationInputs = [
  {
    label: "University Name",
    name: "universityName",
    type: "text",
    value: "",
    pattern: "^[a-zA-Z0-9&.\\- ']{3,100}$",
    placeholder: "University of Lagos",
    required: true,
    hasValidValue: false,
    id: 1,
  },
  {
    label: "University Location",
    name: "universityLocation",
    type: "text",
    value: "",
    pattern: "^[a-zA-Z0-9,.\\-\\/ ]{2,50}$",
    placeholder: "Lagos",
    required: true,
    hasValidValue: false,
    id: 2,
  },
  {
    label: "Degree / Program",
    name: "degree",
    type: "text",
    pattern: "^[a-zA-Z0-9\\/&.\\-' ]{2,100}$",
    value: "",
    placeholder: "Bachelor of Science",
    required: true,
    hasValidValue: false,
    id: 3,
  },
  {
    label: "Field of Study",
    name: "fieldOfStudy",
    type: "text",
    pattern: "^[a-zA-Z0-9\\/&.\\-' ]{2,70}$",
    value: "",
    placeholder: "Computer Science",
    required: true,
    hasValidValue: false,
    id: 4,
  },
  [
    {
      label: "Graduastion Month",
      name: "graduationMonth",
      type: "number",
      value: "",
      min: 1,
      max: 12,
      placeholder: "1",
      required: true,
      hasValidValue: false,
      id: 5,
    },
    {
      label: "Graduation Year",
      name: "graduationYear",
      type: "number",
      min: 1900,
      max: new Date().getFullYear(),
      value: "",
      placeholder: "1900",
      required: true,
      hasValidValue: false,
      id: 6,
    },
  ],
];

export const contactInfoInputs = [
  {
    label: "Phone Number",
    name: "phoneNumber",
    type: "tel",
    pattern: "^\\+?[\\d\\-(). ]{7,20}$",
    value: "",
    placeholder: "+1 (123) 456-7890",
    required: true,
    hasValidValue: false,
    id: 5,
  },
  {
    label: "Linkedin Profile Link",
    name: "linkedin",
    type: "text",
    pattern: "^(https?:\\/\\/(www\\.)?)?linkedin\\.com\\/.*$",
    value: "",
    placeholder: "www.linkedin.com/in/moamal-alaa",
    required: true,
    hasValidValue: false,
    id: 6,
  },
  {
    label: "GitHub Profile Link",
    name: "github",
    type: "text",
    pattern: "^(https?:\\/\\/(www\\.)?)?github\\.com\\/[A-Za-z0-9_-]+\\/?$",
    value: "",
    placeholder: "github.com/Moamal-2000",
    required: true,
    hasValidValue: false,
    id: 7,
  },
  {
    label: "Portfolio Link",
    name: "portfolio",
    type: "text",
    pattern: "^https?:\\/\\/.+$",
    value: "",
    placeholder: "moamalalaa.netlify.app",
    required: false,
    hasValidValue: false,
    id: 8,
  },
];

export const certificationInputs = [
  {
    label: "Certification 1",
    name: "certification1",
    type: "text",
    value: "",
    pattern: "^[a-zA-Z0-9\\/&.\\-#' ]{2,100}$",
    placeholder: "Certificate of Engineering",
    required: false,
    hasValidValue: true,
    id: 1,
  },
  {
    label: "Certification 2",
    name: "certification2",
    type: "text",
    pattern: "^[a-zA-Z0-9\\/&.\\-#' ]{2,100}$",
    value: "",
    placeholder: "Certificate of Engineering",
    required: false,
    hasValidValue: true,
    id: 2,
  },
  {
    label: "Certification 3",
    name: "certification3",
    type: "text",
    pattern: "^[a-zA-Z0-9\\/&.\\-#' ]{2,100}$",
    value: "",
    placeholder: "Certificate of Engineering",
    required: false,
    hasValidValue: true,
    id: 3,
  },
];
